[programs.localnet]
cropper_staking = "3LENVKyJfTQeh6U714NQKYvqEibjqZLPZYfprZsAoCUS"

[programs.devnet]
cropper_staking = "3LENVKyJfTQeh6U714NQKYvqEibjqZLPZYfprZsAoCUS"

[programs.testnet]
cropper_staking = "3cjoBZpiEe49TiFcyvPVBTmR5GxiYzpGmw2HyJyszphw"

[programs.mainnet]
cropper_staking = "FBHjXGXUa65hSCzyfMhkcLzu2U3HByNqcWMuDUUHURLa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "test-keypair.json"

[scripts]
test = "mocha -t 1000000 tests/staking_test.js"