[programs.localnet]
cropper_staking = "3LENVKyJfTQeh6U714NQKYvqEibjqZLPZYfprZsAoCUS"

[programs.devnet]
cropper_staking = "94fsNRJx5pcXxcmWXW2RR3bHbT7SAmhfdZGxm4GLwC1"

[programs.testnet]
cropper_staking = "3cjoBZpiEe49TiFcyvPVBTmR5GxiYzpGmw2HyJyszphw"

[programs.mainnet]
cropper_staking = "2rogd26htJY3BpKhnZnYuqyzQf6SYYGVCy7K7KvRpPAN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "test-keypair.json"

[scripts]
test = "mocha -t 1000000 tests/staking_test.js"